const http = require('http');

const url = 'http://localhost:3000/api/gdrive/proxy?fileId=1lw96Yl-Gfrih3CnduEUQnCnwSFdL-caQ';

http.get(url, (res) => {
  let bodyChunks = [];
  res.on('data', (chunk) => bodyChunks.push(chunk));
  res.on('end', () => {
    const buffer = Buffer.concat(bodyChunks);
    const pdfText = buffer.toString('binary');
    
    // Count occurrences of "/Type/Page" or "/Type /Page"
    const pageMatches = pdfText.match(/\/Type\s*\/Page\b/g);
    console.log('Number of page object matches (/Type/Page):', pageMatches ? pageMatches.length : 0);

    // Let's also check if it's a PDF generated by jsPDF
    const isJsPdf = pdfText.includes('jsPDF');
    console.log('Generated by jsPDF?', isJsPdf);
    
    // Let's check for /Count in /Pages
    const countMatch = pdfText.match(/\/Count\s+(\d+)/);
    if (countMatch) {
      console.log('Pages count (/Count):', countMatch[1]);
    }
  });
});
